name: "Build and Deploy"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm i
      - name: Build Code
        run: npm run build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: .next
          if-no-files-found: error
          retention-days: 1
          include-hidden-files: true
  deploy:
    name: Deploy to Vercel
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .next
      - name: Deploy
        env:
          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
        run: |
          npm i -g vercel
          vercel --prebuilt --prod --yes --token $VERCEL_TOKEN
